### ISSUE TITLE
Does this plugin support recurring payments?

### ISSUE THREAD

**Issue by dionsnoeijen** [studioespresso/craft-mollie-payments#39] opened 2021-08-06 15:35 UTC
We need single donations as well as recurring donations, is this supported? https://docs.mollie.com/payments/recurring

Thank you!

(sorry, just see the other request)...

**Comment by janhenckens** [comment] 2021-08-06 15:50
Single donations are supported, recurring payments are not for now. I've done a couple of custom implementations of this but haven't had the time yet to make something more generic.

**Comment by janhenckens** [comment] 2021-08-06 15:50
Duplicate of #1.

**Comment by srosenbrand** [comment] 2024-05-30 21:50
Hi Jan, it seems recurring payments are still not supported. Any outlook if it will ever be in the plugin? Or have some custom code to get it working?

Regular payment was flawless and super easy with the plugin, but for our website we need the option for yearly donations...

Hope you can give some support!

**Comment by janhenckens** [comment] 2024-05-31 07:25
Hey @srosenbrand

I've built this outside of the plugin a number of times, but haven't had the time recently to look at abstracting it so it could fit in this plugin. 

In most cases I've done this, there was some kind of business logic or specific condition - that would require custom development to be done, which in the end was easier then adding it to the plug-in.

But I'll reopen the issue and have look again. Would you be open to giving some feedback on the concept I come up with @srosenbrand?

**Comment by srosenbrand** [comment] 2024-05-31 08:28
@janhenckens that would be awesome and I am fully open to giving feedback for sure!

**Comment by janhenckens** [comment] 2024-09-05 18:16
Finally added this in the latest Craft 5 version - docs can be found here https://studioespresso.github.io/craft-mollie-payments/subscription-getting-started.html

**Closed by janhenckens** 2024-09-05 18:16 UTC
